#include <print>

#include "xml_input.h"

#include "wxl.gen.h"

import std;

namespace {

// Files the previous run produced but this one didn't: a narrowed profile
// would otherwise leave stale wrappers lying next to the current ones,
// compiling (they're on the include path) but listed nowhere. Only files
// carrying the generator's own banner are removed -- anything a human put
// in the output directory is left alone.
void prune_stale(Output const& out, gen::Emitted const& emitted) {
    std::set<std::string> const current{emitted.files().begin(), emitted.files().end()};

    for (auto&& entry : std::filesystem::directory_iterator{out.dir}) {
        if (!entry.is_regular_file() || current.count(entry.path().filename().string())) {
            continue;
        }

        std::ifstream file{entry.path()};
        std::string first;
        if (!std::getline(file, first) || !first.starts_with("// Generated by winui-srcgen")) {
            continue;
        }
        file.close();

        std::error_code ec;
        if (std::filesystem::remove(entry.path(), ec)) {
            std::print("removed stale {}\n", entry.path().string());
        } else {
            std::print(stderr, "warning: cannot remove stale {}: {}\n", entry.path().string(),
                       ec.message());
        }
    }
}

// The closure's types by category, in the closure's own dependency order:
// category grouping only splits that one ordering into slices, it never
// re-sorts.
gen::type_kinds kinds_of(Closure const& closure) {
    gen::type_kinds kinds;
    for (auto&& type : closure.ordered) {
        switch (md::get_category(type)) {
            case md::category::enum_type:
                kinds.enums.push_back(type);
                break;
            case md::category::struct_type:
                kinds.structs.push_back(type);
                break;
            case md::category::class_type:
                kinds.classes.push_back(type);
                break;
            case md::category::interface_type:
                if (closure.listed_interfaces.contains(type)) {
                    kinds.listed_interfaces.push_back(type);
                }
                break;
            case md::category::delegate_type:
                break;  // no output of their own
        }
    }
    return kinds;
}

}  // namespace

Model analyze(Closure const& closure, ProfileSet const& profiles) {
    auto const kinds = kinds_of(closure);

    Model model;
    model.property_names = closure.property_names;
    model.event_names = closure.event_names;

    gen::analyze_tags(model);
    gen::analyze_enums_and_structs(kinds, closure, model);
    auto const index = gen::analyze_classes(kinds, closure, model);
    gen::analyze_event_args(kinds, closure, index, model);

    // The dictionaries are read once and the writers pick what they know:
    // styles here, brushes there, and whatever a resource of another kind
    // needs when its writer appears.
    for (auto&& dictionary : profiles.resources) {
        auto declared = dictionary_resources(dictionary);
        model.resources.insert(model.resources.end(), std::move_iterator{declared.begin()},
                               std::move_iterator{declared.end()});
    }

    // A dictionary names a target type, and a brush key starts with one, by
    // its bare name; a profile names a class by its full one. The class joins
    // the two -- the first of a name, where two namespaces share it.
    for (auto&& type : kinds.classes) {
        std::string name{type.TypeName()};
        model.class_names.insert(name);
        if (auto const filter = profiles.styles.find(full_name(type)); filter != profiles.styles.end()) {
            model.style_filters.emplace(std::move(name), filter->second);
        }
    }
    model.brushes = profiles.brushes;
    return model;
}

void write_all(Output const& out, Model const& model) {
    std::filesystem::create_directories(out.dir);

    gen::Emitted emitted;
    gen::write_key_enums(out, model, emitted);
    gen::write_tags(out, model, emitted);
    gen::write_enums_and_structs(out, model, emitted);
    gen::write_classes(out, model, emitted);
    gen::write_dsl(out, model.dsl, emitted);
    gen::write_schema(out, model, emitted);
    gen::write_event_args(out, model, emitted);
    gen::write_styles(out, model, emitted);
    gen::write_brushes(out, model, emitted);
    gen::write_alias_index(out, model.resources, emitted);
    gen::write_symbols(out, emitted);

    // Last: drop whatever a previous run left behind, then list everything
    // this run produced.
    prune_stale(out, emitted);
    gen::write_cmake_lists(out, emitted);
}
