#include <print>

#include "xml_input.h"

#include "wxl.gen.h"

import std;

namespace {

// Files the previous run produced but this one didn't: a narrowed profile
// would otherwise leave stale wrappers lying next to the current ones,
// compiling (they're on the include path) but listed nowhere. Only files
// carrying the generator's own banner are removed -- anything a human put
// in the output directory is left alone.
void prune_stale(output const& out, gen::emitted const& em) {
    std::set<std::string> const current{em.files().begin(), em.files().end()};

    for (auto&& entry : std::filesystem::directory_iterator{out.dir}) {
        if (!entry.is_regular_file() || current.count(entry.path().filename().string())) {
            continue;
        }

        std::ifstream file{entry.path()};
        std::string first;
        if (!std::getline(file, first) || !first.starts_with("// Generated by winui-srcgen")) {
            continue;
        }
        file.close();

        std::error_code ec;
        if (std::filesystem::remove(entry.path(), ec)) {
            std::print("removed stale {}\n", entry.path().string());
        } else {
            std::print(stderr, "warning: cannot remove stale {}: {}\n", entry.path().string(),
                       ec.message());
        }
    }
}

// The closure's types by category, in the closure's own dependency order:
// category grouping only splits that one ordering into slices, it never
// re-sorts.
gen::type_kinds kinds_of(closure const& cl) {
    gen::type_kinds kinds;
    for (auto&& type : cl.ordered) {
        switch (md::get_category(type)) {
            case md::category::enum_type:
                kinds.enums.push_back(type);
                break;
            case md::category::struct_type:
                kinds.structs.push_back(type);
                break;
            case md::category::class_type:
                kinds.classes.push_back(type);
                break;
            case md::category::interface_type:
                if (cl.listed_interfaces.contains(type)) {
                    kinds.listed_interfaces.push_back(type);
                }
                break;
            case md::category::delegate_type:
                break;  // no output of their own
        }
    }
    return kinds;
}

}  // namespace

model analyze(closure const& cl, profile_set const& profiles, type_map const& types,
              std::vector<symbol> symbols) {
    auto const kinds = kinds_of(cl);

    model m;
    m.property_names = cl.property_names;
    m.event_names = cl.event_names;
    m.from_text = profiles.from_text;
    m.replaced_calls = profiles.replaced_calls;

    gen::analyze_tags(types, m);
    gen::analyze_enums_and_structs(kinds, cl, types, m);
    auto const index = gen::analyze_classes(kinds, cl, types, m);
    gen::analyze_event_args(kinds, cl, index, m);

    // The dictionaries are read once and the writers pick what they know:
    // styles here, brushes there, and whatever a resource of another kind
    // needs when its writer appears.
    for (auto&& dictionary : profiles.resources) {
        auto declared = dictionary_resources(dictionary);
        m.resources.insert(m.resources.end(), std::move_iterator{declared.begin()},
                           std::move_iterator{declared.end()});
    }

    // A dictionary names a target type, and a brush key starts with one, by
    // its bare name; a profile names a class by its full one. The class joins
    // the two -- the first of a name, where two namespaces share it.
    for (auto&& type : kinds.classes) {
        std::string name{type.TypeName()};
        m.class_names.insert(name);
        if (auto const filter = profiles.styles.find(full_name(type)); filter != profiles.styles.end()) {
            m.style_filters.emplace(std::move(name), filter->second);
        }
    }
    m.brushes = profiles.brushes;
    m.symbols = std::move(symbols);
    return m;
}

void write_all(output const& out, model const& m) {
    std::filesystem::create_directories(out.dir);

    gen::emitted em;
    gen::write_key_enums(out, m, em);
    gen::write_tags(out, m, em);
    gen::write_enums_and_structs(out, m, em);
    gen::write_classes(out, m, em);
    gen::write_dsl(out, m.dsl, em);
    gen::write_schema(out, m, em);
    gen::write_event_args(out, m, em);
    gen::write_styles(out, m, em);
    gen::write_brushes(out, m, em);
    gen::write_alias_index(out, m.resources, em);
    gen::write_symbols(out, m, em);

    // Last: drop whatever a previous run left behind, then list everything
    // this run produced.
    prune_stale(out, em);
    gen::write_cmake_lists(out, em);
}
