#include <format>
#include <print>

#include "xml_input.h"

#include "wxl.gen.h"

import std;

namespace {

// Files the previous run produced but this one didn't: a narrowed profile
// would otherwise leave stale wrappers lying next to the current ones,
// compiling (they're on the include path) but listed nowhere. Only files
// carrying the generator's own banner are removed -- anything a human put
// in the output directory is left alone.
void prune_stale(Output const& out, gen::Emitted const& emitted) {
    std::set<std::string> const current{emitted.files().begin(), emitted.files().end()};

    for (auto&& entry : std::filesystem::directory_iterator{out.dir}) {
        if (!entry.is_regular_file() || current.count(entry.path().filename().string())) {
            continue;
        }

        std::ifstream file{entry.path()};
        std::string first;
        if (!std::getline(file, first) || !first.starts_with("// Generated by winui-srcgen")) {
            continue;
        }
        file.close();

        std::error_code ec;
        std::filesystem::remove(entry.path(), ec);
        std::print("removed stale {}\n", entry.path().string());
    }
}

}  // namespace

// Orchestration only -- the order the artefacts are written in. Each step
// lives in its own gen/*.cpp; see gen/writers.h.

void write_all(Output const& out, Model const& model,
               std::vector<std::filesystem::path> const& resource_dictionaries) {
    std::filesystem::create_directories(out.dir);

    gen::Emitted emitted;
    gen::write_collections(out, emitted);
    gen::write_key_enums(out, model, emitted);
    gen::write_tags(out, model, emitted);
    gen::write_enums_and_structs(out, model, emitted);
    gen::write_interfaces(out, model, emitted);

    // The args views come after the classes: which file declares a type, and
    // which Collection specializations already have a definition, is settled
    // by the class writer, and an args member's signature may name either.
    gen::ClassOutput classes;
    gen::write_classes(out, model, emitted, classes);
    gen::write_event_args(out, model, classes, emitted);

    // The dictionaries are read once and the writers pick what they know:
    // styles here, brushes there, and whatever a resource of another kind
    // needs when its writer appears.
    std::vector<DictionaryResource> resources;
    for (auto&& dictionary : resource_dictionaries) {
        auto declared = dictionary_resources(dictionary);
        resources.insert(resources.end(), std::move_iterator{declared.begin()},
                         std::move_iterator{declared.end()});
    }
    gen::write_styles(out, model, resources, emitted);
    gen::write_brushes(out, model, resources, emitted);
    gen::write_alias_index(out, resources, emitted);
    gen::write_symbols(out, emitted);

    // Last: drop whatever a previous run left behind, then list everything
    // this run produced.
    prune_stale(out, emitted);
    gen::write_cmake_lists(out, emitted);
}
