auto gameSettings = NavigationViewItem {
    content = u"Game Settings",
    // In a NavigationViewItem the control sets the states of the icon itself.
    icon = AnimatedIcon {
        AnimatedSettingsVisualSource {},
        fallbackIconSource = FontIconSource {glyph = u"\uE713"},
    },
};

auto example = StackPanel {
    TextBlock {
        textWrapping = TextWrapping::WrapWholeWords,
        Margin {0, 0, 0, 24},
        u"If you set an AnimatedIcon as the value of the Icon property, the NavigationViewItem will set the states "
        u"of the AnimatedIcon for you, according to the states of the control. For guidance on how to properly "
        u"structure your animation file see the AnimatedIcon Guidance page.\n\n"
        u"For this example, this sets a custom animation GameSettingsIcon that was generated by the LottieGen tool.",
    },
    NavigationView {isSettingsVisible = false, menuItems[gameSettings]},
};