# ---- Documentation sites, built by CMake ----
#
# Doxygen and nothing layered on top of it. The reasoning is written out in
# solutions.md under "Документация"; the one fact that decides it is that
# wxl.core and wxl.async are C++20 modules, Doxygen 1.18 is the
# only generator that renders them as modules, and every post-processor of its
# XML -- m.css, sourcey, moxygen, breathe, doxybook2 -- drops kind="module".
#
# Two entry points:
#   wxl_doxygen_bootstrap()   -- resolve the tool and the theme, once per tree
#   wxl_add_doxygen_site(...) -- one target per site
#
# Both are meant to be used from outside this tree as well: Bukvitsa includes
# this file the same way it already includes vcpkg_bootstrap.cmake and
# wxl_helpers.cmake, and builds its own site plus wxl's tag file with it.

include_guard(GLOBAL)
include(FetchContent)

set(WXL_DOXYGEN_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}" CACHE INTERNAL "")

# 1.18.0 is the first release that turns `export module` into a module page.
# Earlier ones parse .ixx happily and quietly produce nothing for the module
# itself, which is the half-working case worth failing on rather than living
# with.
set(WXL_DOXYGEN_MIN_VERSION 1.18.0)

# The pinned fallback build, used when the host has nothing new enough. That is
# the normal case rather than the exception: 1.18.0 is weeks old, so requiring
# a system install would mean requiring an install nobody has yet.
set(WXL_DOXYGEN_URL
    "https://www.doxygen.nl/files/doxygen-1.18.0.windows.x64.bin.zip")
set(WXL_DOXYGEN_SHA256
    "e84f54cfd49ef06b0b16536056dbec0c496323de28abcce53a4269463de35eaf")

# jothepro/doxygen-awesome-css, master at 2026-05-31 (past the v2.4.2 tag).
# Pinned by commit for the same reason winmd is in the root CMakeLists: a tag
# can move, a commit cannot, and a theme that changes under us changes every
# page at once.
set(WXL_DOXYGEN_AWESOME_COMMIT "82d315e34ac419a81caccf470cc2fbc2ec8ee524")

set(WXL_DOXYGEN_AWESOME_SCRIPTS
    doxygen-awesome-darkmode-toggle.js
    doxygen-awesome-fragment-copy-button.js
    doxygen-awesome-paragraph-link.js
    doxygen-awesome-interactive-toc.js)

# Where the pages fetch mermaid from. One place, for the header patched below
# and for the Doxyfile: Doxygen's own header block is replaced with ours (see
# the patch), so the two had better name the same script.
set(WXL_DOXYGEN_MERMAID_JS_URL
    "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs")

# The theme's JavaScript has to be pulled in from the page header, and Doxygen
# offers no "extra head" setting -- HTML_HEADER replaces the whole header.
# Writing one by hand would pin us to one Doxygen's markup, so the header is
# generated by the very Doxygen we are about to run and then patched. Doing it
# at configure time rather than as a build step keeps the site target a single
# command, and lets a test run Doxygen directly without building anything first.
function(wxl_doxygen_bootstrap)
    # Everything the cache remembers is checked, not just believed: a fetch that
    # failed halfway leaves the cache entry pointing at a directory that is gone,
    # and the site then fails at build time with seven "does not exist" errors
    # instead of re-fetching here.
    if(EXISTS "${WXL_DOXYGEN_EXECUTABLE}"
       AND EXISTS "${WXL_DOXYGEN_HTML_HEADER}"
       AND EXISTS "${WXL_DOXYGEN_THEME_DIR}/doxygen-awesome.css"
       AND NOT "${WXL_DOXYGEN_CMAKE_DIR}/wxl_doxygen.cmake" IS_NEWER_THAN "${WXL_DOXYGEN_HTML_HEADER}")
        return()
    endif()

    find_package(Doxygen ${WXL_DOXYGEN_MIN_VERSION} QUIET)
    if(DOXYGEN_FOUND)
        set(_doxygen "${DOXYGEN_EXECUTABLE}")
        message(STATUS "Doxygen ${DOXYGEN_VERSION}: ${_doxygen}")
    elseif(WIN32)
        FetchContent_Declare(wxl_doxygen
            URL "${WXL_DOXYGEN_URL}"
            URL_HASH "SHA256=${WXL_DOXYGEN_SHA256}"
            DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
        FetchContent_MakeAvailable(wxl_doxygen)
        set(_doxygen "${wxl_doxygen_SOURCE_DIR}/doxygen.exe")
        message(STATUS "Doxygen ${WXL_DOXYGEN_MIN_VERSION} (fetched): ${_doxygen}")
    else()
        message(FATAL_ERROR
            "Doxygen ${WXL_DOXYGEN_MIN_VERSION} or newer is needed to build the "
            "documentation and none was found. Only the Windows build is fetched "
            "automatically; install it and re-configure.")
    endif()

    FetchContent_Declare(wxl_doxygen_awesome
        GIT_REPOSITORY https://github.com/jothepro/doxygen-awesome-css.git
        GIT_TAG ${WXL_DOXYGEN_AWESOME_COMMIT})
    FetchContent_MakeAvailable(wxl_doxygen_awesome)

    # Generated with the default configuration on purpose: what varies between
    # sites (title, search box, tree) sits in Doxygen's own $placeholders and is
    # resolved per page at build time, so one header serves every site.
    set(_scratch "${CMAKE_BINARY_DIR}/docs/.header")
    file(MAKE_DIRECTORY "${_scratch}")
    execute_process(
        COMMAND "${_doxygen}" -w html header.html footer.html style.css
        WORKING_DIRECTORY "${_scratch}"
        RESULT_VARIABLE _res
        OUTPUT_QUIET
        ERROR_VARIABLE _err)
    if(NOT _res EQUAL 0)
        message(FATAL_ERROR "doxygen -w html failed: ${_err}")
    endif()

    set(_inject "")
    foreach(_script IN LISTS WXL_DOXYGEN_AWESOME_SCRIPTS)
        string(APPEND _inject
            "<script type=\"text/javascript\" src=\"$relpath^${_script}\"></script>\n")
    endforeach()
    string(APPEND _inject "<script type=\"text/javascript\">\n")
    string(APPEND _inject "  DoxygenAwesomeDarkModeToggle.init();\n")
    string(APPEND _inject "  DoxygenAwesomeFragmentCopyButton.init();\n")
    string(APPEND _inject "  DoxygenAwesomeParagraphLink.init();\n")
    string(APPEND _inject "  DoxygenAwesomeInteractiveToc.init();\n")
    string(APPEND _inject "</script>\n")

    file(READ "${_scratch}/header.html" _html)
    string(REPLACE "</head>" "${_inject}</head>" _html "${_html}")

    # Doxygen's own $mermaidjs block initialises mermaid without deterministicIds,
    # and mermaid then names every SVG it renders mermaid-<Date.now()>: two
    # diagrams rendered within the same millisecond share an id, and the later
    # one is drawn into the earlier one's box -- three sequence diagrams on one
    # page were enough to see it. So the block is ours: the same URL and theme
    # Doxygen would have written, plus the one option. The header is rebuilt
    # whenever this file is newer than it (the check at the top), so a change
    # here reaches a configured tree without anyone deleting the cache.
    set(_mermaid "<script type=\"module\">\n")
    string(APPEND _mermaid "import mermaid from '${WXL_DOXYGEN_MERMAID_JS_URL}';\n")
    string(APPEND _mermaid
        "mermaid.initialize({ startOnLoad: true, theme: 'default', deterministicIds: true });\n")
    string(APPEND _mermaid "</script>")
    string(REPLACE "$mermaidjs" "${_mermaid}" _html "${_html}")

    set(_header "${CMAKE_BINARY_DIR}/docs/header.html")
    file(WRITE "${_header}" "${_html}")

    set(WXL_DOXYGEN_EXECUTABLE "${_doxygen}"
        CACHE FILEPATH "Doxygen used to build the documentation" FORCE)
    set(WXL_DOXYGEN_THEME_DIR "${wxl_doxygen_awesome_SOURCE_DIR}"
        CACHE PATH "doxygen-awesome-css checkout" FORCE)
    set(WXL_DOXYGEN_HTML_HEADER "${_header}"
        CACHE FILEPATH "Doxygen page header, patched with the theme's scripts" FORCE)
    mark_as_advanced(WXL_DOXYGEN_EXECUTABLE WXL_DOXYGEN_THEME_DIR WXL_DOXYGEN_HTML_HEADER)
endfunction()

# Quotes each entry and lays them out one per line, the way Doxygen's config
# parser wants them: paths with spaces are ordinary here (Program Files, a user
# name in Cyrillic), and an unquoted one silently splits into two inputs that do
# not exist -- which Doxygen reports as nothing at all.
function(_wxl_doxygen_quote out)
    set(_result "")
    foreach(_item IN LISTS ARGN)
        string(APPEND _result " \\\n                         \"${_item}\"")
    endforeach()
    set(${out} "${_result}" PARENT_SCOPE)
endfunction()

# wxl_add_doxygen_site(<target>
#     PROJECT_NAME <name> [BRIEF <text>] [LANGUAGE <Doxygen language>]
#     INPUT <path>...  [EXCLUDE <pattern>...]  [STRIP_FROM <dir>]
#     [MAINPAGE <file.md>] [OUTPUT <dir>]
#     [TAGFILE <file>]        -- write one, for other sites to link against
#     [TAGS <file>=<url>...]  -- read others, turning mentions into links
#     [DEPENDS <target>...])
#
# The target is never part of ALL: documentation is built when asked for, not on
# every build of the library.
function(wxl_add_doxygen_site target)
    cmake_parse_arguments(A
        ""
        "PROJECT_NAME;BRIEF;LANGUAGE;STRIP_FROM;MAINPAGE;OUTPUT;TAGFILE"
        "INPUT;EXCLUDE;TAGS;DEPENDS"
        ${ARGN})

    wxl_doxygen_bootstrap()

    if(NOT A_OUTPUT)
        set(A_OUTPUT "${CMAKE_BINARY_DIR}/docs/${target}")
    endif()
    if(NOT A_LANGUAGE)
        set(A_LANGUAGE English)
    endif()

    _wxl_doxygen_quote(DOXY_INPUT ${A_INPUT})
    _wxl_doxygen_quote(DOXY_EXCLUDE_PATTERNS ${A_EXCLUDE})
    _wxl_doxygen_quote(DOXY_TAGFILES ${A_TAGS})

    set(DOXY_PROJECT_NAME     "${A_PROJECT_NAME}")
    set(DOXY_PROJECT_BRIEF    "${A_BRIEF}")
    set(DOXY_LANGUAGE         "${A_LANGUAGE}")
    set(DOXY_OUTPUT_DIRECTORY "${A_OUTPUT}")
    set(DOXY_STRIP_FROM_PATH  "${A_STRIP_FROM}")
    set(DOXY_MAINPAGE         "${A_MAINPAGE}")
    set(DOXY_GENERATE_TAGFILE "${A_TAGFILE}")
    set(DOXY_HTML_HEADER      "${WXL_DOXYGEN_HTML_HEADER}")
    set(DOXY_MERMAID_JS_URL   "${WXL_DOXYGEN_MERMAID_JS_URL}")
    set(DOXY_WARN_LOGFILE     "${CMAKE_BINARY_DIR}/docs/${target}.warnings.log")

    _wxl_doxygen_quote(DOXY_HTML_EXTRA_STYLESHEET
        "${WXL_DOXYGEN_THEME_DIR}/doxygen-awesome.css"
        "${WXL_DOXYGEN_THEME_DIR}/doxygen-awesome-sidebar-only.css"
        "${WXL_DOXYGEN_THEME_DIR}/doxygen-awesome-sidebar-only-darkmode-toggle.css")

    set(_extra_files "")
    foreach(_script IN LISTS WXL_DOXYGEN_AWESOME_SCRIPTS)
        list(APPEND _extra_files "${WXL_DOXYGEN_THEME_DIR}/${_script}")
    endforeach()
    _wxl_doxygen_quote(DOXY_HTML_EXTRA_FILES ${_extra_files})

    set(_doxyfile "${CMAKE_BINARY_DIR}/docs/${target}.Doxyfile")
    configure_file("${WXL_DOXYGEN_CMAKE_DIR}/Doxyfile.in" "${_doxyfile}" @ONLY)

    # No OUTPUT/DEPENDS pair: a stale site is worse than a redundant two-second
    # run, and getting the dependency list right would mean globbing every tree
    # the site reads on every build anyway.
    add_custom_target(${target}
        COMMAND "${WXL_DOXYGEN_EXECUTABLE}" "${_doxyfile}"
        COMMENT "Doxygen: ${A_PROJECT_NAME} -> ${A_OUTPUT}/html"
        VERBATIM)
    if(A_DEPENDS)
        add_dependencies(${target} ${A_DEPENDS})
    endif()

    set_property(TARGET ${target} PROPERTY FOLDER docs)
    set_property(TARGET ${target} PROPERTY WXL_DOXYFILE "${_doxyfile}")
endfunction()

# A test that the documentation builds clean. It runs the same Doxyfile the
# target does, and the Doxyfile makes warnings fatal, so what it asserts is that
# no comment in the tree is malformed -- an unclosed <code>, a Windows path
# whose backslash reads as a command, a @param naming an argument that was
# renamed. Those are invisible in the source and visible only here.
function(wxl_add_doxygen_test target)
    get_target_property(_doxyfile ${target} WXL_DOXYFILE)
    add_test(NAME ${target} COMMAND "${WXL_DOXYGEN_EXECUTABLE}" "${_doxyfile}")
endfunction()
