# /cmake/wxl_app_icon.cmake

include_guard(GLOBAL)

# Puts an application's icon inside its executable, from one line beside the
# target:
#
#     wxl_target_icon(sample.quadratic Assets/x2.ico)
#
# Windows keeps a program's icon in the executable itself, as a resource, and a
# resource gets there through a script the RC compiler reads. That script holds
# nothing but the path to the .ico, so there is nothing in it worth writing by
# hand or keeping in step: it is generated into the build tree and added to the
# target's sources. MSVC turns the RC language on by itself, so no
# enable_language() is needed, and the .rc is compiled and linked the way the
# .manifest beside it already is.
#
# The icon takes resource id 1 on purpose. The shell shows the icon with the
# lowest id, wxl::TrayIcon looks that id up when an application hands it no icon
# of its own, and wxl puts the same one on windows that carry none (see
# wxl.ui/src/impl/app_icon.h). One call, and the executable, the windows and the
# tray show the same picture.
function(wxl_target_icon target icon)
    if(NOT WIN32)
        return()
    endif()

    get_filename_component(_icon "${icon}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

    if(NOT EXISTS "${_icon}")
        message(FATAL_ERROR "wxl_target_icon(${target}): no icon file at ${_icon}")
    endif()

    # The path goes into the script as a C string, where a backslash escapes
    # whatever follows it -- so every separator is doubled.
    file(TO_NATIVE_PATH "${_icon}" _native)
    string(REPLACE "\\" "\\\\" _quoted "${_native}")

    set(_script "${CMAKE_CURRENT_BINARY_DIR}/${target}.icon.rc")

    file(CONFIGURE
        OUTPUT "${_script}"
        CONTENT "// Generated by wxl_target_icon(); an edit here does not survive CMake.\n1 ICON \"${_quoted}\"\n"
        @ONLY)

    target_sources(${target} PRIVATE "${_script}")

    # The script names the picture and says nothing about its content, so the
    # dependency is stated here: replacing the .ico rebuilds the resource.
    set_source_files_properties("${_script}" PROPERTIES OBJECT_DEPENDS "${_icon}")
endfunction()
